/* CRITERIA

1. SPA - Single Page Application

2. ToDo - App

3. KOMMENTOI

--------- TARVITAAN --------------

ELEMENTIT :
  - VALIKKO

  - NÄKYMÄT :
    - ETUSIVU-ELEMENTTI
    - INFO-ELEMENTTI

  - TEHTÄVÄT:
    - TEHTÄVÄ - OTSIKKO
    - TEHTÄVÄ - KUVAUS
    - TEHTÄVÄ - PÄIVÄYS
    - CONTAINER - KAIKKI TEHTÄVÄT
    - CONTAINER - YKSITTÄINEN TEHTÄVÄ
    - NAPPI - TEHTÄVIEN LISÄYS
    - NAPPI - TEHTÄVIEN POISTO
    - TAGIT / LUOKAT (ERI VÄREJÄ)
    - NAPPI - SUORITETTU TEHTÄVÄ

TOIMINNALLISUUDET :
  - VALIKKO :
    - NAVIGOINTI NÄKYMIEN VÄLILLÄ

  - TEHTÄVÄLISTA :
    - UUDELLEENJÄRJESTYS LUOKKIEN/TAGIEN PERUSTEELLA
    - TEHTÄVÄLISTA ILMAN SUODATUSTA (KAIKKI TEHTÄVÄT NÄKYVÄT)

  - TEHTÄVÄT :
    - TEHTÄVIEN MERKKAUS SUORITETUKSI (EI POISTA)
    - TEHTÄVIEN LISÄYS LISTALLE
    - TEHTÄVIEN POISTO LISTALTA++++++++++++++++++++++++++++++
    - TEHTÄVIEN MUOKKAAMINEN
    - TEHTÄVIEN UUDELLEENJÄRJESTYS LISTALLA (DRAG & DROP)
    - LUOKITTELU (TAGS) EI ENNALTAMÄÄRÄTTYJÄ!


DOKUMENTAATIO :
  - doc.pdf
  - INFO NÄKYMÄ - KÄYTTÖOHJEET
  - INFO NÄKYMÄ - LISENSSIT
  - INFO-NÄKYMÄ - TEKIJÄN NIMI




*/

import Todo from "./components/Todo";

function App() {
  return (
    <div className="App">
      <Todo />
    </div>
  );
}

export default App;
